variables: 
    USER_PROJECT: onlineshop
    IMAGE_VERSION: ${CI_REGISTRY}/${REPOSITORY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}

stages:
    - build 
    - push
    - deploy

build: 
    stage: build
    variables:
        GIT_STRATEGY: clone 
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script: 
        - docker build -t $IMAGE_VERSION .
    after_script:
        - docker logout $CI_REGISTRY
    tags:
        - taoone-shared-dev-shell
    only:
        - tags

push: 
    stage: push
    variables:
        GIT_STRATEGY: none 
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script: 
        - docker push $IMAGE_VERSION
    after_script:
        - docker logout $CI_REGISTRY
    tags:
        - taoone-shared-dev-shell
    only:
        - tags

deploy: 
    stage: deploy
    variables:
        GIT_STRATEGY: none 
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script: 
        -   docker pull $IMAGE_VERSION
        -   sudo docker rm -f ${REPOSITORY}-${CI_PROJECT_NAME}; sudo docker run --env-file ${ENV_PATH} --name ${REPOSITORY}-${CI_PROJECT_NAME} -dp 7777:7777 $IMAGE_VERSION
    after_script:
        - docker logout $CI_REGISTRY
    tags:
        - taoone-shared-syshub-dev1-shell
    only: 
        - tags
